### ISSUE TITLE
question 

### ISSUE THREAD

**Issue by ORCA666** [xinbailu/DripLoader#2]
hello. its me again :p 

so this time i ain't wasting time, and jumping directly to development, and adding modifications.
but i noticed it is getting detected as Driploz ... whatever.
even tho i just compiled it. (i was not testing it with a pid or so).
my question is, and since it is being detected statically and not during run time, what do u think the cause ?
(ill be changing the xor key. both AllocationGranularity & PageSize sizes as a first attempt )

im asking this to gain some time, so if u could help, and directly jump to the cause. ill be thankful.

thanks for this code !

**Comment by ORCA666** [comment]
update : 
so i stripped all useless functions (i mean to the purpose of process injection)
and i changed the xor key [its still int] as well as AllocationGranularity & PageSize sizes [when u do it manually [here](https://github.com/xinbailu/DripLoader/blob/37a70d0666cef74329739a3d097c2f5cac68bd72/DripLoader/DripLoader.cpp#L309)]
i also changed [VC_PREF_BASES](https://github.com/xinbailu/DripLoader/blob/37a70d0666cef74329739a3d097c2f5cac68bd72/DripLoader/DripLoader.h#L24) altho i just added useless addresses :P for the sake of testing
but windows defender still flagged it.

**Comment by xinbailu** [comment]
Hey @ORCA666, the Microsoft signatures are for the ASM part with direct syscalls. Others I have no idea.

**Comment by ORCA666** [comment]
so its getting detected as wacatac now : https://github.com/jthuraisamy/SysWhispers2/issues/6 
i am working on the solution :) if u want to help i will have np at the end my code is based on yours, and on yours blog .

**Comment by xinbailu** [comment]
Can you message me on Twitter? Would be easier to talk

**Comment by xinbailu** [comment]
In any case, you can get a cleaned-up and undetected version here: https://github.com/xinbailu/DripLoader-Ops

**Comment by ORCA666** [comment]
@xinbailu are u saying I'm one of the script kiddies u made that repo for ?

**Comment by xinbailu** [comment]
@ORCA666 yes, the only one for now in fact 🤣

**Comment by ORCA666** [comment]
I almost gave u respect. U think I cant code it by myself like that? Ur bypassing the av with Michel Jackson's as a string, I was changing the whole code. So who is the kid now

**Comment by xinbailu** [comment]
just kidding dude, michael jackson is a great AV bypass tho

**Comment by ORCA666** [comment]
im just fucking around, ill dm u twitter.
